### ISSUE TITLE
Remove `pronamic_pay_omnikassa_2_merchant_return_url` filter?

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-rabo-smart-pay#26]
I just discovered that the `.test` TLD is now valid in the `merchantReturnURL` parameter, while this resulted in an error in the past:

> merchantReturnURL is not a valid web address

Other TLD's such as `.site` and `.dev` seem valid too, but I'm not sure if these were not allowed before. If this is also true for production, maybe we can then remove the `pronamic_pay_omnikassa_2_merchant_return_url` filter as it is no longer needed?

https://github.com/pronamic/wp-pronamic-pay-omnikassa-2/blob/4afc90d4b2789c137acf6f36239891ff06cf6465/src/Gateway.php#L268-L288

https://github.com/pronamic/wp-pronamic-pay-omnikassa-2/blob/4afc90d4b2789c137acf6f36239891ff06cf6465/documentation/README.md?plain=1#L3-L21

**Comment by remcotolsma** [comment]
Psalm don't like this filter:

```
ERROR: HookNotFound - src/Integration.php:124:8 - Hook "pronamic_pay_omnikassa_2_merchant_return_url" not found
		if ( \has_filter( 'pronamic_pay_omnikassa_2_merchant_return_url' ) ) {
```

**Comment by remcotolsma** [comment]
Removed in ae58afdb5997fa68cabadec4fe8026ddcd98941a and 6671e028331a9e44f919976ffc30b2134f709707.
