### ISSUE TITLE
Add support for `skipHppResultPage` parameter

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-rabo-smart-pay#37]
From customer:

> We've included your solution to connect to the Smart Pay API by Rabobank to our client's site. Unfortunately Rabo now shows a double "thank you" screen after successful payment. They contacted us and told us we can easily fix this by changing a setting `skipHppResultPage` to `true`.
> 
> Unfortunately we can't find any setting in Pay to change this API flag nor any other way to set/add this manually. Is there any way we can enable this?

We could add support for this parameter in the gateway settings? What do you think, @remcotolsma?

_Internal ticket: https://freescout.pronamic.nl/conversation/352_

**Comment by remcotolsma** [comment]
Yes, I can imagine that users would like to configure this flag.

https://github.com/rabobank-nederland/omnikassa-sdk-doc/blob/cdb39a30165ab70498f36aacaa13845e9a2d0035/README.md?plain=1#L230
